version: "3.8"

services:
  db:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: idesign
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
    ports:
      - "3308:3306" # 호스트의 3308 포트를 컨테이너의 3306 포트에 매핑
    volumes:
      - db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/idesign
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    ports:
      - "80:8080"
    depends_on:
      - db

volumes:
  db-data:
