version: "3.8"

services:
  db:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: idesign
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
    ports:
      - "3308:3306" # 호스트의 3308 포트를 컨테이너의 3306 포트에 매핑
    volumes:
      - db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  app1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-app1
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/idesign
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    ports:
      - "8081:8080" # 호스트의 8081 포트를 컨테이너의 8080 포트에 매핑
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test:
        ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  # app2:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: spring-app2
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/idesign
  #     SPRING_DATASOURCE_USERNAME: root
  #     SPRING_DATASOURCE_PASSWORD: 1234
  #   ports:
  #     - "8082:8080" # 호스트의 8082 포트를 컨테이너의 8080 포트에 매핑
  #   depends_on:
  #     - db

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80" # Nginx가 사용할 포트
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      app1:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

volumes:
  db-data:
