version: "3.8"

services:
  db:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: idesign
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
    ports:
      - "3308:3306" # 호스트의 3308 포트를 컨테이너의 3306 포트에 매핑
    volumes:
      - db-data:/var/lib/mysql
      - ./init.sql:/docker-e

volumes:
  db-data:
