version: "3.8"

services:
  app1:
    image: yoonjaehwan/idesign:latest
    container_name: idesign_blue
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/idesign
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    ports:
      - "8081:8080"
