version: "3.8"

services:
  app2:
    image: yoonjaehwan/idesign:latest
    container_name: idesign_green
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/idesign
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    ports:
      - "8082:8080"
