version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80" # Nginx가 사용할 포트
    volumes:
      - ./nginx/nginx.blue.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
