version: "3.8"

services:
  # db:
  #   image: mariadb:latest
  #   container_name: mariadb
  #   environment:
  #     MYSQL_ROOT_PASSWORD: 1234
  #     MYSQL_DATABASE: idesign
  #     MYSQL_USER: root
  #     MYSQL_PASSWORD: 1234
  #   ports:
  #     - "3308:3306" # 호스트의 3308 포트를 컨테이너의 3306 포트에 매핑

  idesign_green:
    image: yoonjaehwan/idesign:latest
    container_name: idesign_green
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://13.125.128.143:3306/idesign
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1q2w3e4r!@#$
    ports:
      - "8082:8080"
